# Header

menu:
  主页: /
  归档: /archives
  相册: /photos
  #随笔: /tags/随笔/
  #分类: /categories
  #标签: /tags

# SubNav
subnav:
  github: "https://github.com/MarkChenyyds"
  zhihu: "https://www.zhihu.com/people/wan-ju-xiong-zhi-mi"
  mail: "mailto:markchen_98@qq.com"
  rss: "atom.xml"
  #weibo: ""
  #psn: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

#rss:

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: "more"
show_all_link: "展开全文"
fancybox: true
mathjax: false

# 打赏1
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
reward_wording: "请我喝杯咖啡"
alipay: /assets/img/alipay.jpg
weixin: /assets/img/weixinpay.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: "目录，不存在的…"

# 是否有快速回到顶部的按钮
top: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
baidu_analytics: "f3119e6a4320fc4766f0d145d156f38a"
google_analytics: "G-KJFWQL4MYJ"
favicon: /assets/img/earth.ico #页面主题小图标

#你的头像url
avatar: /assets/img/lanyangyang_new.jpg

#头像是否旋转(如果不要旋转取false)
avatarrotation: true

#是否开启分享
share_jia: false

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#请参考wiki：

#1、多说
#duoshuo: "litten-hexo"

#2、网易云跟帖
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3、畅言
#changyan_appid: "cysX3aGWt"
#changyan_conf: "prod_1dcda447175aada96edcdb7e412338fa"

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
#disqus: false

#6、Valine https://valine.js.org
valine:
  appid: HTCqiUDSsPSLkrN899Kx9ZZv-MdYXbMMI
  appkey: jd5O7cOZVvi21naKzDqjzYxV
  verify: false #验证码，verify和notify这两个最好就别动了
  notify: true #评论回复提醒
  avatar: monsterid #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 欢迎评论 ^_^ #评论框占位符
  enable: true # 设置为true，默认为false
  pageSize: 10 # 分页大小，10页就自动分页
  visitor: true # 是否允许游客评论 ，进入官网查看设置：https://valine.js.org/visitor.html

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 右滑板块背景
  #slider: "linear-gradient(200deg,#a0cfe4,#e8c37e)"
  slider: "linear-gradient(200deg,#E1FFFF,#008080)"
  # 左侧头像板块动态图效果
  gif:
    # 是否启用
    enable: false
    # 自定义背景图路径(默认可以不设置，提供默认背景图biubiubiu.gif)
    path: /assets/img/mrfz.gif
  # 头像上面的背景颜色 e.g. linear-gradient(rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.5))
  # header: '#D3D1DC'
  header: "rgba(176,244,230,1)" #设置背景透明度，不然头像上方是默认色
  #左侧头像板块的背景颜色(IE兼容设置：filter:alpha(opacity=80);)
  left_ground:
    enable: true
    default: "rgba(173,216,230,1)"
    # url: "url(/assets/img/funingna.jpg) no-repeat 100%;background-size:cover;opacity:0.8;filter:alpha(opacity=80);"
  # 正文的背景颜色(IE兼容设置：opacity:0.8;filter:alpha(opacity=80);)
  article_ground:
    enable: true
    default: "rgba(95, 158, 160, 1)" #设置背景透明度
    #url: "url(/assets/img/funingna.jpg) no-repeat 100%;background-size:cover;opacity:0.7;filter:alpha(opacity=70);"

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 是否开启字数统计
#不需要使用，直接设置值为false，或注释掉
word_count: true

# 是否开启访问量统计功能(不蒜子)
busuanzi:
  enable: true

# 音乐
# 简单的网易云音乐
simple_163_music:
  enable: true

# 心知天气
xinzhi_weather: true

# #看板娘（不知道为啥，放在这模型会变）
# live2d:
#   enable: true
#   scriptFrom: local
#   pluginRootPath: live2dw/
#   pluginJsPath: lib/
#   pluginModelPath: assets/
#   tagMode: false
#   debug: false
#   model:
#     use: live2d-widget-model-nipsilon
#   display:
#     position: right
#     width: 150
#     height: 300
#   mobile:
#     show: true
#   react:
#     opacity: 0.7

# 动态线条效果，会向鼠标集中
canvas_nest:
  enable: false
  color: "206, 187, 95"
  pointColor: "249, 72, 97"
  opacity: "0.9"
  count: "136"
  zIndex: "-1"

# 飘雪特效
# https://github.com/MlgmXyysd/snow.js
snow: true

# 鼠标点击烟花爆炸效果
fireworks: true

# 百度推送
baidu_push: true

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: "所有文章"
  aboutme: "关于我"
  #friends: "友情链接"

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: MarkChen<br>道法自然<br/>
